### ISSUE TITLE
Some CLI args don't work as module args

### ISSUE THREAD

**Issue by shacker** [redacted/XKCD-password-generator#27]
This works from command line:

```$ xkcdpass --valid_chars='[a-j]'```

but doesn't work when using xkcdpass as a module:

```
>>> print(xp.generate_xkcdpassword(mywords, valid_chars='[a-j]'))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: generate_xkcdpassword() got an unexpected keyword argument 'valid_chars'
```

**Comment by bittner** [comment]
Hi Scott, `valid_chars` is / must be passed to [generate_wordlist()](https://github.com/redacted/XKCD-password-generator/blob/master/xkcdpass/xkcd_password.py#L115), which is [used in main()](https://github.com/redacted/XKCD-password-generator/blob/master/xkcdpass/xkcd_password.py#L308). That's why it works from the command line.

What you have to do is create a word list first, and pass it into the generate function, as described in the [Advanced Usage](https://github.com/redacted/XKCD-password-generator#advanced-usage) of the README.

**Comment by shacker** [comment]
Ah yes, just figured that out - some of the CLI args go with generate_wordlist(), others go with generate_xkcdpassword(). Not too hard to figure out by trial and error, but a bit more documentation on that difference might be helpful. 

But no, this is not a bug. Thanks!

**Comment by shacker** [comment]
However,  I get the "unexpected argument" error if I put `numwords=5` on either of the calls - that one doesn't seem to be supported in the module at all.

**Comment by bittner** [comment]
Stack trace?

**Comment by bittner** [comment]
In fact, you could make a PR and change the `n_words` argument to `numwords` to make variable names consistent. Go for it!

**Comment by redacted** [comment]
You are completely correct that the consistency between CLI and module use could be better. Thank you for the PR, I will merge it ASAP and push an updated version to pypi.
